project:
  type: website

website:
  title: "Teresa Kubacka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: consulting.qmd
        text: Consulting 
      - href: speaking.qmd
        text: Workshops and talks 
      - href: writing.qmd 
        text: Writing 
      - href: contact.qmd 
        text: Get in touch  


format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    mainfont: Jost

 

