---
title: "Workshops, tutorials, keynotes"
subtitle: "Hire me as a trainer or speaker"
format:
  html:
    toc: true
---

## Workshops and Training  

### Offer 

::: {.service-list}
#### Data visualization and storytelling
I am an experienced teacher of data visualization and data storytelling. I offer several workshop packages tailored to the needs of analysts and developers, as well as a data storytelling workshop for a general audience.

#### Interdisciplinary workshops
I offer interdisciplinary workshops that build a bridge between different specializations, such as: 

- Applied machine learning for academics.  
- Scientific method and analytics for developers.   
- UX for data scientists.  

#### Custom workshops
I will be happy to prepare and deliver a custom tailored workshop on a topic related to data science.

#### Facilitation
I facilitate discovery workshops for analytics using a variety of collaborative discovery methods such as Design Thinking and EventStorming.
::: 

### Examples of past workshops  

My experience includes designing and teaching of: 

- A 15-week data visualization course, targeted for mid-bachelor-level data scientists 
- Multiple data visualization workshops for the participants of a JS developer bootcamp 
- Crash-courses on data visualization for scientific communication
- Data visualization workshops for a broad audience, eg. [at Impact Hub Zurich](#vid-impacthub) 
- Crash-courses of Quarto for scientific communication, eg. [Coffee Lecture at the ETH Library](#vid-coffee-quarto) 
- A half-day data storytelling course at a CAS (Certificate of Advanced Studies) for experienced data professionals
- Workshops on particular aspects of data science, eg. a [Workshop on statistical feature engineering](https://appliedmldays.org/events/amld-epfl-2021/workshops/back-to-the-feature-boost-your-ml-model-with-statistical-feature-engineering) led together with Magdalena Surówka at Applied Machine Learning Days 2021 in Lausanne, or a 2-day workshop on machine learning for astrophysicists 
- Multiple workshops co-prepared and co-run together with the WiMLDS Zurich 
- Many internal workshops led at a client site e.g. as part of the requirements collection process 

I am constantly improving my skills by attending workshops myself, e.g. Design Sprint training by [DAY8](https://day8.io/), UX and Design Thinking workshops by [Bonanza Design](https://www.bonanza-studios.com/), Problem Framing Training by [Design Sprint Academy](https://www.designsprint.academy/), EventStorming Remote Modelling by [Avanscoperta](https://www.avanscoperta.it). 


## Keynotes and Talks  

I deliver keynotes, impulse lectures and take part in panel discussions on topics related to AI, data science, in particular when concerning the impact of data on society and the human side of data science. 

Some past assignments include: 

- A keynote at [Kongress der Deutschen Marktforschung 2023](https://www.bvm.org/termine-weiterbildung/kongress-der-deutschen-marktforschung/nachlese/) in Frankfurt am Main, Germany - *Human-made data and machine-generated content: How to remain positively skeptical in times of quantified world*  
- A lightning talk at the [Open Data Forum 2023](https://opendata.ch/events/opendata-ch-2023-forum/) in Zurich, Switzerland - *Open Scholarly Metadata* ([slides here](https://opendata.ch/wordpress/files/2023/07/2023-06-16-Open-scholarly-metadata-export.pdf)) 
- An invited talk at the [Sino-Swiss Workshop on Research Integrity](https://swissnex.org/app/uploads/sites/10/2023/05/Sino-Swiss-Workshop-on-Research-Integrity-20230510.pdf) - *The Role of Bibliometrics in Safeguarding Research Integrity: Perspectives of the Libraries*
- An impulse lecture at [ETH Library Learn & Talk 2023](https://video.ethz.ch/events/2023/learn_and_talk/90baa469-f65d-4f9f-99c6-01d8e2e163de.html) - *Könnte eine KI das Studium an der ETH erfolgreich abschliessen* ([watch here](#vid-bibliothek-ki))
- A lightning talk at the [NormConf](https://normconf.com/) - *How to stop crying when using Matplotlib* ([watch here](#vid-normconf)) 
- A talk on [World Usability Days 2020](https://uxschweiz.ch/events/world-usability-day-2020/) in Rapperswil, Switzerland - *Explainable AI for ordinary humans* ([watch here](#vid-explainable-wud))  




## Watch Online  

:::  {.video-centered #vid-impacthub} 

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q1_xEFo2OJM?si=Y2lzjKRA5fhk7_5M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<figcaption class="figure-caption">Workshop at Impact Hub Zurich, 2020</figcaption>
::: 


:::  {.video-centered #vid-explainable-wud} 
<iframe width="560" height="315" src="https://www.youtube.com/embed/TsEQHyBU1N0?si=9Bzvfeaxpsp2pr8j" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<figcaption class="figure-caption">Talk on the Swiss edition of World Usability Days, 2020</figcaption>
::: 

:::  {.video-centered #vid-normconf} 
<iframe width="560" height="315" src="https://www.youtube.com/embed/vjQIaepijbE?si=P7GZVAY_99ui_BAx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<figcaption class="figure-caption">NormConf Lightning Talk, 2022</figcaption>
::: 

:::  {.video-centered #vid-coffee-quarto} 
<iframe width="560" height="315" src="https://www.youtube.com/embed/l204f-lsuDo?si=wNXxB-my9oOZVS5S" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<figcaption class="figure-caption">Coffee Lecture at the ETH Library, 2022</figcaption>
::: 


:::  {.video-centered #vid-bibliothek-ki} 
<iframe width="560" height="315" src="https://video.ethz.ch/etc/designs/mmp/video/player.html?id=90baa469-f65d-4f9f-99c6-01d8e2e163de" frameborder="0" allowfullscreen></iframe>
<figcaption class="figure-caption">An impulse lecture about AI in Academia at the ETH Library, 2023 (in German) [link](https://video.ethz.ch/events/2023/learn_and_talk/90baa469-f65d-4f9f-99c6-01d8e2e163de.html)</figcaption>
::: 